### ISSUE TITLE
[BUG] Change comments order to descrent date

### ISSUE THREAD

**Issue by guilmour** [libreflix/libreflix#5]

**Comment by glblapco** [comment]
Opa! Já tem alguém trabalhando nesse bug?

**Comment by guilmour** [comment]
> Opa! Já tem alguém trabalhando nesse bug?

Ainda não, maninho.

Pode pegar. E ser algum probleminha só avisar que tentamos juntos. Tá com aquele problema estranho do container.

**Comment by glblapco** [comment]
> > Opa! Já tem alguém trabalhando nesse bug?
> 
> Ainda não, maninho.
> 
> Pode pegar. E ser algum probleminha só avisar que tentamos juntos. Tá com aquele problema estranho do container.

Beleza, ainda não consegui subir o container aqui mas estou fazendo a correção enquanto isso, consegue colocar no meu nome ali no "assignees", por favor? Acho que não tenho permissão
